"""
CAT Prep Reader - single-folder Flask app.

Run:
    python app.py
Then open http://localhost:5000

Folder layout expected:
    articles/<category-slug>/part-<n>.md   (generated by generate_article.py)
"""

import re
import os
import json
import sqlite3
from pathlib import Path
from datetime import date, timedelta
import requests
from generate_article import OPENROUTER_URL, VOCAB_MODEL

import frontmatter
import markdown as md
from flask import Flask, render_template, redirect, url_for, session, request
_lookup_cache = {}

app = Flask(__name__)
app.secret_key = "cat-prep-dev-secret"  # fine for local use; change if you ever deploy this

BASE_DIR = Path(__file__).parent
ARTICLES_DIR = BASE_DIR / "articles"
DB_PATH = BASE_DIR / "progress.db"

USERS = {
    "shobhana": {"label": "Shobhana", "theme": "lavender"},
    "faiz": {"label": "Faiz", "theme": "ocean"},
}


# ---------- DB ----------

def get_db():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db():
    conn = get_db()
    conn.execute(
        """CREATE TABLE IF NOT EXISTS progress (
            user TEXT NOT NULL,
            category TEXT NOT NULL,
            part INTEGER NOT NULL,
            completed_at TEXT NOT NULL,
            PRIMARY KEY (user, category, part)
        )"""
    )
    conn.commit()
    conn.close()

# Initialize database when the app is imported
init_db()

def mark_complete(user, category, part):
    conn = get_db()
    conn.execute(
        "INSERT OR REPLACE INTO progress (user, category, part, completed_at) VALUES (?, ?, ?, ?)",
        (user, category, part, date.today().isoformat()),
    )
    conn.commit()
    conn.close()


def get_completed(user):
    conn = get_db()
    rows = conn.execute("SELECT category, part, completed_at FROM progress WHERE user = ?", (user,)).fetchall()
    conn.close()
    return {(r["category"], r["part"]): r["completed_at"] for r in rows}


def get_streak(user):
    conn = get_db()
    rows = conn.execute(
        "SELECT DISTINCT completed_at FROM progress WHERE user = ? ORDER BY completed_at DESC", (user,)
    ).fetchall()
    conn.close()
    dates = {date.fromisoformat(r["completed_at"]) for r in rows}
    if not dates:
        return 0

    today = date.today()
    cursor = today if today in dates else today - timedelta(days=1)
    if cursor not in dates:
        return 0

    streak = 0
    while cursor in dates:
        streak += 1
        cursor -= timedelta(days=1)
    return streak


# ---------- Article loading ----------

def parse_article_file(path: Path):
    post = frontmatter.load(path)
    raw_body = post.content

    if "## Word Bank" in raw_body:
        body_md, word_section = raw_body.split("## Word Bank", 1)
    else:
        body_md, word_section = raw_body, ""

    body_md = body_md.rsplit("---", 1)[0] if body_md.strip().endswith("---") else body_md

    words = []
    for block in re.split(r"^### ", word_section, flags=re.MULTILINE)[1:]:
        lines = block.strip().splitlines()
        word = lines[0].strip()
        meaning_match = re.search(r"\*\*Meaning:\*\*\s*(.+)", block)
        example_match = re.search(r"\*\*Example:\*\*\s*(.+)", block)
        words.append(
            {
                "word": word,
                "meaning": meaning_match.group(1).strip() if meaning_match else "",
                "example": example_match.group(1).strip() if example_match else "",
            }
        )

    body_html = md.markdown(body_md.strip())

    # wrap vocab words in clickable spans (whole-word, case-insensitive, first form only)
    for w in words:
        pattern = re.compile(rf"\b({re.escape(w['word'])})\b", re.IGNORECASE)
        body_html = pattern.sub(
            rf'<span class="vocab-word" data-word="{w["word"]}">\1</span>', body_html, count=3
        )

    return {
        "title": post.get("title", path.stem),
        "source": post.get("source", ""),
        "category": post.get("category", path.parent.name),
        "part": post.get("part", 0),
        "body_html": body_html,
        "words": words,
    }


def load_all_articles():
    """Returns {category: [article_dict, ...]} sorted by part number."""
    categories = {}
    if not ARTICLES_DIR.exists():
        return categories
    for cat_dir in sorted(ARTICLES_DIR.iterdir()):
        if not cat_dir.is_dir():
            continue
        parts = []
        for md_file in sorted(cat_dir.glob("part-*.md")):
            parts.append(parse_article_file(md_file))
        parts.sort(key=lambda a: a["part"])
        categories[cat_dir.name] = parts
    return categories
def lookup_word_ai(word: str, context: str = "") -> dict:
    """Ask the LLM to define a single word the student selected, using surrounding
    sentence as context for accuracy (handles homonyms / usage-specific meaning)."""
    key = word.lower().strip()
    if key in _lookup_cache:
        return _lookup_cache[key]

    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        raise RuntimeError("OPENROUTER_API_KEY not set")

    prompt = f"""A student reading an article for CAT exam prep selected the word "{word}"
because they don't know it. Here is the sentence it appeared in for context:

"{context}"

Return ONLY valid JSON (no markdown fences, no preamble) with keys:
- "word": the word, lowercase base form
- "meaning": a simple one-line dictionary-style definition, matching how it's used in that sentence
- "example": ONE short original example sentence using the word (different from the one given)
"""

    resp = requests.post(
        OPENROUTER_URL,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        json={
            "model": VOCAB_MODEL,
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0.3,
        },
        timeout=30,
    )
    resp.raise_for_status()
    raw = resp.json()["choices"][0]["message"]["content"]
    cleaned = re.sub(r"^```json|```$", "", raw.strip(), flags=re.MULTILINE).strip()

    match = re.search(r"\{.*\}", cleaned, re.DOTALL)
    parsed = json.loads(match.group(0)) if match else {"word": word, "meaning": "", "example": ""}

    _lookup_cache[key] = parsed
    return parsed

def generate_quiz_questions(words: list[dict]) -> list[dict]:
    """Given a list of {word, meaning, example} dicts, ask the AI to produce one
    quiz question per word, alternating between fill-in-the-blank and
    write-your-own-sentence types."""
    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        raise RuntimeError("OPENROUTER_API_KEY not set")

    trimmed = words[:10]  # cap to keep prompt + cost reasonable

    prompt = f"""You are building a vocabulary quiz for a CAT exam student, based on these words
and their meanings:

{json.dumps(trimmed)}

For EACH word, produce exactly ONE question, alternating type (start with "fill_blank"):
- "fill_blank": write an original sentence that uses the word's meaning, but replace the
  word itself with a blank "____". The sentence must make it clear from context which
  word fits. Do not reuse the word anywhere else in the sentence.
- "sentence_use": write a short instruction like: Write a sentence using the word "X".

Return ONLY a valid JSON array (no markdown fences, no preamble), one object per word:
[{{"word": "...", "meaning": "...", "type": "fill_blank" or "sentence_use", "prompt": "..."}}]
"""

    resp = requests.post(
        OPENROUTER_URL,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        json={
            "model": VOCAB_MODEL,
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0.5,
        },
        timeout=60,
    )
    resp.raise_for_status()
    raw = resp.json()["choices"][0]["message"]["content"]
    cleaned = re.sub(r"^```json|```$", "", raw.strip(), flags=re.MULTILINE).strip()

    match = re.search(r"\[.*\]", cleaned, re.DOTALL)
    return json.loads(match.group(0)) if match else []


def check_sentence_usage(word: str, meaning: str, sentence: str) -> dict:
    """Grades a student's original sentence for correct usage of a target word."""
    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        raise RuntimeError("OPENROUTER_API_KEY not set")

    prompt = f"""A student was asked to write a sentence using the word "{word}"
(meaning: {meaning}).

Their sentence: "{sentence}"

Judge whether they used the word correctly in context and with roughly the right meaning.
Minor grammar issues are fine — focus on whether the word's meaning was used appropriately.

Return ONLY valid JSON (no markdown fences, no preamble):
{{"correct": true or false, "feedback": "one short, encouraging sentence explaining why"}}
"""

    resp = requests.post(
        OPENROUTER_URL,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        json={
            "model": VOCAB_MODEL,
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0.3,
        },
        timeout=30,
    )
    resp.raise_for_status()
    raw = resp.json()["choices"][0]["message"]["content"]
    cleaned = re.sub(r"^```json|```$", "", raw.strip(), flags=re.MULTILINE).strip()

    match = re.search(r"\{.*\}", cleaned, re.DOTALL)
    return json.loads(match.group(0)) if match else {"correct": False, "feedback": "Couldn't grade that — moving on."}

@app.route("/api/lookup", methods=["POST"])
def api_lookup():
    if "user" not in session:
        return {"error": "not logged in"}, 401

    data = request.get_json(silent=True) or {}
    word = (data.get("word") or "").strip()
    context = (data.get("context") or "").strip()

    if not word or len(word) > 40 or not word.replace("-", "").isalpha():
        return {"error": "invalid word"}, 400

    try:
        result = lookup_word_ai(word, context)
        return result
    except Exception as e:
        print("Lookup error:", e)
        return {"error": "lookup failed"}, 500

# ---------- Routes ----------

@app.route("/")
def home():
    if "user" not in session:
        return render_template("choose_user.html", users=USERS)
    return redirect(url_for("dashboard"))


@app.route("/user/<name>")
def set_user(name):
    if name not in USERS:
        return redirect(url_for("home"))
    session["user"] = name
    return redirect(url_for("dashboard"))

@app.route("/api/quiz/generate", methods=["POST"])
def api_quiz_generate():
    if "user" not in session:
        return {"error": "not logged in"}, 401

    data = request.get_json(silent=True) or {}
    words = data.get("words", [])
    if not words:
        return {"error": "no words provided"}, 400

    try:
        questions = generate_quiz_questions(words)
        return {"questions": questions}
    except Exception as e:
        print("Quiz generation error:", e)
        return {"error": "quiz generation failed"}, 500


@app.route("/api/quiz/check", methods=["POST"])
def api_quiz_check():
    if "user" not in session:
        return {"error": "not logged in"}, 401

    data = request.get_json(silent=True) or {}
    word = (data.get("word") or "").strip()
    meaning = (data.get("meaning") or "").strip()
    sentence = (data.get("sentence") or "").strip()

    if not word or not sentence:
        return {"error": "missing word or sentence"}, 400
    if len(sentence) > 300:
        return {"error": "sentence too long"}, 400

    try:
        result = check_sentence_usage(word, meaning, sentence)
        return result
    except Exception as e:
        print("Quiz check error:", e)
        return {"error": "check failed"}, 500


@app.route("/dashboard")
def dashboard():
    if "user" not in session:
        return redirect(url_for("home"))
    user = session["user"]
    categories = load_all_articles()
    completed = get_completed(user)
    streak = get_streak(user)

    display = {}
    for cat, parts in categories.items():
        rows = []
        unlocked = True
        for a in parts:
            is_done = (cat, a["part"]) in completed
            rows.append({**a, "done": is_done, "unlocked": unlocked})
            if not is_done:
                unlocked = False
        display[cat] = rows

    return render_template(
        "dashboard.html",
        categories=display,
        streak=streak,
        user=USERS[user]["label"],
        theme=USERS[user]["theme"],
    )

@app.route("/healthz")
def healthz():
    return {"status": "ok"}, 200

@app.route("/article/<category>/<int:part>")
def article(category, part):
    if "user" not in session:
        return redirect(url_for("home"))
    user = session["user"]
    path = ARTICLES_DIR / category / f"part-{part}.md"
    if not path.exists():
        return "Article not found", 404

    completed = get_completed(user)

    # enforce sequential unlock
    if part > 1 and (category, part - 1) not in completed:
        return redirect(url_for("dashboard"))

    art = parse_article_file(path)
    return render_template(
        "article.html",
        art=art,
        category=category,
        part=part,
        done=(category, part) in completed,
        theme=USERS[user]["theme"],
    )


@app.route("/complete/<category>/<int:part>", methods=["POST"])
def complete(category, part):
    if "user" not in session:
        return redirect(url_for("home"))
    mark_complete(session["user"], category, part)
    return redirect(url_for("dashboard"))


@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("home"))


if __name__ == "__main__":
    init_db()
    app.run(host="0.0.0.0", port=int(os.environ.get("PORT", 5000)))
